services:
    microsoft_graph.client:
        class: TotalCRM\MicrosoftGraph\DependencyInjection\MicrosoftGraphClient
        arguments: ['@request_stack', '@service_container']

    microsoft_graph.request:
        class: TotalCRM\MicrosoftGraph\DependencyInjection\MicrosoftGraphRequest
        arguments: ["@microsoft_graph.client"]

    microsoft_graph.calendar:
        class: TotalCRM\MicrosoftGraph\Service\Calendar
        arguments: ["@microsoft_graph.request"]

    microsoft_graph.redirect_exception_listener:
        class: TotalCRM\MicrosoftGraph\EventListener\RedirectExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception }

    microsoft_graph.session_storage:
        class: TotalCRM\MicrosoftGraph\Token\SessionStorage
        arguments: ["@session", '@service_container']
